### Data Preprocessing

In [1]:
import pandas as pd
merged_df = pd.read_csv('final_cleaned_merge_imputed.csv')
merged_df.head()

,Unnamed: 0,Variety,Reason,Year,Study,Location,ZS49PlHt,ZS49 (no days),GrYld(kg/ha),D1H00051861,...,L7H657085535,L7H657085541,L7H657104991,L7H657131781,L7H657146353,L7H657146356,L7H657147154,L7H657147171,L7H657147173,L7H657156298
0,0,Commander,1,0,5,4,55.0,92.0,NaN,1,...,1,1,1,1,1,1,0,1,1,1
1,1,Commander,1,0,0,4,38.0,63.0,NaN,1,...,1,1,1,1,1,1,0,1,1,1
2,5,Commander,1,2,3,4,NaN,NaN,NaN,1,...,1,1,1,1,1,1,0,1,1,1
3,6,Commander,1,2,0,4,70.0,85.0,NaN,1,...,1,1,1,1,1,1,0,1,1,1
4,7,Commander,1,1,4,1,56.9,77.0,2410.5,1,...,1,1,1,1,1,1,0,1,1,1

In [2]:
merged_df['Study'].unique()

array([5, 0, 3, 4, 1, 2], dtype=int64)

In [3]:
merged_df.shape

(5340, 30552)

In [4]:
merged_df.drop(merged_df.columns[0], axis=1, inplace=True)

In [5]:
merged_df.head()

,Variety,Reason,Year,Study,Location,ZS49PlHt,ZS49 (no days),GrYld(kg/ha),D1H00051861,D1H000263584,...,L7H657085535,L7H657085541,L7H657104991,L7H657131781,L7H657146353,L7H657146356,L7H657147154,L7H657147171,L7H657147173,L7H657156298
0,Commander,1,0,5,4,55.0,92.0,NaN,1,1,...,1,1,1,1,1,1,0,1,1,1
1,Commander,1,0,0,4,38.0,63.0,NaN,1,1,...,1,1,1,1,1,1,0,1,1,1
2,Commander,1,2,3,4,NaN,NaN,NaN,1,1,...,1,1,1,1,1,1,0,1,1,1
3,Commander,1,2,0,4,70.0,85.0,NaN,1,1,...,1,1,1,1,1,1,0,1,1,1
4,Commander,1,1,4,1,56.9,77.0,2410.5,1,1,...,1,1,1,1,1,1,0,1,1,1

In [6]:
dataset_zs49 = merged_df.copy()
dataset_yield = merged_df.copy()

In [7]:
dataset_zs49.shape

(5340, 30551)

In [8]:
dataset_zs49.drop(columns=['ZS49PlHt','GrYld(kg/ha)'], inplace=True)
dataset_zs49.head()

,Variety,Reason,Year,Study,Location,ZS49 (no days),D1H00051861,D1H000263584,D1H000275564,D1H000277624,...,L7H657085535,L7H657085541,L7H657104991,L7H657131781,L7H657146353,L7H657146356,L7H657147154,L7H657147171,L7H657147173,L7H657156298
0,Commander,1,0,5,4,92.0,1,1,1,1,...,1,1,1,1,1,1,0,1,1,1
1,Commander,1,0,0,4,63.0,1,1,1,1,...,1,1,1,1,1,1,0,1,1,1
2,Commander,1,2,3,4,NaN,1,1,1,1,...,1,1,1,1,1,1,0,1,1,1
3,Commander,1,2,0,4,85.0,1,1,1,1,...,1,1,1,1,1,1,0,1,1,1
4,Commander,1,1,4,1,77.0,1,1,1,1,...,1,1,1,1,1,1,0,1,1,1

In [9]:
dataset_zs49.iloc[:, :10].isnull().sum()

Variety              0
Reason               0
Year                 0
Study                0
Location             0
ZS49 (no days)    1137
D1H00051861          0
D1H000263584         0
D1H000275564         0
D1H000277624         0
dtype: int64

In [10]:
dataset_zs49.dropna(subset=['ZS49 (no days)'], inplace=True)
dataset_zs49.shape

(4203, 30549)

In [11]:
dataset_zs49.head()

,Variety,Reason,Year,Study,Location,ZS49 (no days),D1H00051861,D1H000263584,D1H000275564,D1H000277624,...,L7H657085535,L7H657085541,L7H657104991,L7H657131781,L7H657146353,L7H657146356,L7H657147154,L7H657147171,L7H657147173,L7H657156298
0,Commander,1,0,5,4,92.0,1,1,1,1,...,1,1,1,1,1,1,0,1,1,1
1,Commander,1,0,0,4,63.0,1,1,1,1,...,1,1,1,1,1,1,0,1,1,1
3,Commander,1,2,0,4,85.0,1,1,1,1,...,1,1,1,1,1,1,0,1,1,1
4,Commander,1,1,4,1,77.0,1,1,1,1,...,1,1,1,1,1,1,0,1,1,1
5,Commander,1,2,4,1,87.9,1,1,1,1,...,1,1,1,1,1,1,0,1,1,1

In [12]:
dataset_zs49.shape

(4203, 30549)

In [13]:
X = dataset_zs49.iloc[:, 6:]
y = dataset_zs49['ZS49 (no days)']

X.shape, y.shape

((4203, 30543), (4203,))

In [15]:
X.head()

,D1H00051861,D1H000263584,D1H000275564,D1H000277624,D1H000277628,D1H000277656,D1H000277673,D1H000278185,D1H000278243,D1H000278386,...,L7H657085535,L7H657085541,L7H657104991,L7H657131781,L7H657146353,L7H657146356,L7H657147154,L7H657147171,L7H657147173,L7H657156298
0,1,1,1,1,1,1,1,1,0,1,...,1,1,1,1,1,1,0,1,1,1
1,1,1,1,1,1,1,1,1,0,1,...,1,1,1,1,1,1,0,1,1,1
3,1,1,1,1,1,1,1,1,0,1,...,1,1,1,1,1,1,0,1,1,1
4,1,1,1,1,1,1,1,1,0,1,...,1,1,1,1,1,1,0,1,1,1
5,1,1,1,1,1,1,1,1,0,1,...,1,1,1,1,1,1,0,1,1,1

In [24]:
dataset_yield.head()

,Variety,Reason,Year,Study,Location,ZS49PlHt,ZS49 (no days),GrYld(kg/ha),D1H00051861,D1H000263584,...,L7H657085535,L7H657085541,L7H657104991,L7H657131781,L7H657146353,L7H657146356,L7H657147154,L7H657147171,L7H657147173,L7H657156298
0,Commander,1,0,5,4,55.0,92.0,NaN,1,1,...,1,1,1,1,1,1,0,1,1,1
1,Commander,1,0,0,4,38.0,63.0,NaN,1,1,...,1,1,1,1,1,1,0,1,1,1
2,Commander,1,2,3,4,NaN,NaN,NaN,1,1,...,1,1,1,1,1,1,0,1,1,1
3,Commander,1,2,0,4,70.0,85.0,NaN,1,1,...,1,1,1,1,1,1,0,1,1,1
4,Commander,1,1,4,1,56.9,77.0,2410.5,1,1,...,1,1,1,1,1,1,0,1,1,1

In [25]:
dataset_yield.shape

(5340, 30551)

In [26]:
dataset_yield.dropna(subset=['GrYld(kg/ha)'], inplace=True)
dataset_yield.shape

(2617, 30551)

In [35]:
X_yield = dataset_yield.iloc[:, 8:]
y_yield = dataset_yield['GrYld(kg/ha)']

X_yield.shape, y_yield.shape

((2617, 30543), (2617,))

### Applying Random Forest on gene data only

In [37]:
import numpy as np
import optuna
from sklearn.model_selection import KFold
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

n_splits = 3
kf = KFold(n_splits=n_splits, shuffle=True, random_state=42)

def objective(trial):
    n_estimators = trial.suggest_int('n_estimators', 0, 700)
    max_depth = trial.suggest_int('max_depth', 10, 100)
    min_samples_split = trial.suggest_int('min_samples_split', 2, 10)
    min_samples_leaf = trial.suggest_int('min_samples_leaf', 1, 10)

    mse = []

    for train_index, test_index in kf.split(X_yield):
        X_train, X_test = X_yield.iloc[train_index], X_yield.iloc[test_index]
        y_train, y_test = y_yield.iloc[train_index], y_yield.iloc[test_index]

        rf_model_yield = RandomForestRegressor(
            n_estimators=n_estimators,
            max_depth=max_depth,
            min_samples_split=min_samples_split, 
            min_samples_leaf=min_samples_leaf,
            n_jobs=-1,
            random_state=42
            )
        
        rf_model_yield.fit(X_train, y_train)

        y_pred = rf_model_yield.predict(X_test)

        mse.append(mean_squared_error(y_test, y_pred))

    return np.mean(mse)

In [38]:
study = optuna.create_study(direction='minimize', study_name='RandomForestRegressorGSyield', storage='sqlite:///optuna_study/RandomForestRegressorGSyield.sqlite3', load_if_exists=True)
study.optimize(objective, n_trials=100, show_progress_bar=True)

[I 2024-09-21 14:34:01,835] A new study created in RDB with name: RandomForestRegressorGSyield

  0%|          | 0/100 [00:00<?, ?it/s]

[I 2024-09-21 14:38:35,867] Trial 0 finished with value: 1080951.3785510946 and parameters: {'n_estimators': 238, 'max_depth': 34, 'min_samples_split': 6, 'min_samples_leaf': 5}. Best is trial 0 with value: 1080951.3785510946.
[I 2024-09-21 14:51:15,505] Trial 1 finished with value: 1091600.4484408807 and parameters: {'n_estimators': 584, 'max_depth': 53, 'min_samples_split': 6, 'min_samples_leaf': 3}. Best is trial 0 with value: 1080951.3785510946.
[I 2024-09-21 15:01:09,572] Trial 2 finished with value: 1071017.1721015472 and parameters: {'n_estimators': 615, 'max_depth': 52, 'min_samples_split': 7, 'min_samples_leaf': 7}. Best is trial 2 with value: 1071017.1721015472.
[I 2024-09-21 15:09:33,910] Trial 3 finished with value: 1090145.8861392827 and parameters: {'n_estimators': 383, 'max_depth': 31, 'min_samples_split': 5, 'min_samples_leaf': 3}. Best is trial 2 with value: 1071017.1721015472.
[I 2024-09-21 15:19:49,836] Trial 4 finished with value: 1062376.2834304103 and parameters: {'n_estimators': 700, 'max_depth': 59, 'min_samples_split': 2, 'min_samples_leaf': 9}. Best is trial 4 with value: 1062376.2834304103.
[I 2024-09-21 15:22:24,377] Trial 5 finished with value: 1100004.3208201027 and parameters: {'n_estimators': 112, 'max_depth': 86, 'min_samples_split': 9, 'min_samples_leaf': 1}. Best is trial 4 with value: 1062376.2834304103.
[I 2024-09-21 15:38:02,094] Trial 6 finished with value: 1097734.1083459116 and parameters: {'n_estimators': 678, 'max_depth': 83, 'min_samples_split': 5, 'min_samples_leaf': 2}. Best is trial 4 with value: 1062376.2834304103.
[I 2024-09-21 15:41:55,665] Trial 7 finished with value: 1077819.6415687862 and parameters: {'n_estimators': 207, 'max_depth': 11, 'min_samples_split': 7, 'min_samples_leaf': 3}. Best is trial 4 with value: 1062376.2834304103.
[I 2024-09-21 15:49:15,148] Trial 8 finished with value: 1085016.7343806974 and parameters: {'n_estimators': 366, 'max_depth': 60, 'min_samples_split': 4, 'min_samples_leaf': 4}. Best is trial 4 with value: 1062376.2834304103.
[I 2024-09-21 15:59:58,057] Trial 9 finished with value: 1106701.675571564 and parameters: {'n_estimators': 396, 'max_depth': 46, 'min_samples_split': 2, 'min_samples_leaf': 1}. Best is trial 4 with value: 1062376.2834304103.
[I 2024-09-21 16:07:04,840] Trial 10 finished with value: 1058011.6390790262 and parameters: {'n_estimators': 505, 'max_depth': 70, 'min_samples_split': 2, 'min_samples_leaf': 10}. Best is trial 10 with value: 1058011.6390790262.
[I 2024-09-21 16:14:23,737] Trial 11 finished with value: 1058020.3574504738 and parameters: {'n_estimators': 515, 'max_depth': 70, 'min_samples_split': 2, 'min_samples_leaf': 10}. Best is trial 10 with value: 1058011.6390790262.
[I 2024-09-21 16:21:04,134] Trial 12 finished with value: 1057444.1939122414 and parameters: {'n_estimators': 469, 'max_depth': 98, 'min_samples_split': 3, 'min_samples_leaf': 10}. Best is trial 12 with value: 1057444.1939122414.
[I 2024-09-21 16:28:31,355] Trial 13 finished with value: 1066127.4073908073 and parameters: {'n_estimators': 484, 'max_depth': 100, 'min_samples_split': 3, 'min_samples_leaf': 8}. Best is trial 12 with value: 1057444.1939122414.
[I 2024-09-21 16:35:20,748] Trial 14 finished with value: 1057767.7579302366 and parameters: {'n_estimators': 485, 'max_depth': 98, 'min_samples_split': 4, 'min_samples_leaf': 10}. Best is trial 12 with value: 1057444.1939122414.
[I 2024-09-21 16:39:47,758] Trial 15 finished with value: 1072112.536350637 and parameters: {'n_estimators': 267, 'max_depth': 100, 'min_samples_split': 4, 'min_samples_leaf': 7}. Best is trial 12 with value: 1057444.1939122414.
[I 2024-09-21 16:46:36,528] Trial 16 finished with value: 1066307.7748337302 and parameters: {'n_estimators': 446, 'max_depth': 87, 'min_samples_split': 4, 'min_samples_leaf': 8}. Best is trial 12 with value: 1057444.1939122414.
[I 2024-09-21 16:47:11,091] Trial 17 finished with value: 1081217.6855874732 and parameters: {'n_estimators': 18, 'max_depth': 75, 'min_samples_split': 10, 'min_samples_leaf': 6}. Best is trial 12 with value: 1057444.1939122414.
[I 2024-09-21 16:51:52,567] Trial 18 finished with value: 1061726.574423772 and parameters: {'n_estimators': 315, 'max_depth': 93, 'min_samples_split': 3, 'min_samples_leaf': 9}. Best is trial 12 with value: 1057444.1939122414.
[I 2024-09-21 17:00:07,733] Trial 19 finished with value: 1058124.6968721305 and parameters: {'n_estimators': 584, 'max_depth': 78, 'min_samples_split': 3, 'min_samples_leaf': 10}. Best is trial 12 with value: 1057444.1939122414.
[I 2024-09-21 17:06:37,865] Trial 20 finished with value: 1061991.8360417164 and parameters: {'n_estimators': 440, 'max_depth': 94, 'min_samples_split': 5, 'min_samples_leaf': 9}. Best is trial 12 with value: 1057444.1939122414.
[I 2024-09-21 17:14:20,358] Trial 21 finished with value: 1058021.7602726503 and parameters: {'n_estimators': 547, 'max_depth': 69, 'min_samples_split': 3, 'min_samples_leaf': 10}. Best is trial 12 with value: 1057444.1939122414.
[I 2024-09-21 17:21:45,705] Trial 22 finished with value: 1066302.4962741544 and parameters: {'n_estimators': 476, 'max_depth': 91, 'min_samples_split': 2, 'min_samples_leaf': 8}. Best is trial 12 with value: 1057444.1939122414.
[I 2024-09-21 17:26:25,105] Trial 23 finished with value: 1057654.1820054264 and parameters: {'n_estimators': 324, 'max_depth': 67, 'min_samples_split': 4, 'min_samples_leaf': 10}. Best is trial 12 with value: 1057444.1939122414.
[I 2024-09-21 17:31:28,119] Trial 24 finished with value: 1061212.5172754612 and parameters: {'n_estimators': 337, 'max_depth': 42, 'min_samples_split': 4, 'min_samples_leaf': 9}. Best is trial 12 with value: 1057444.1939122414.
[I 2024-09-21 17:34:23,079] Trial 25 finished with value: 1071479.974559603 and parameters: {'n_estimators': 172, 'max_depth': 79, 'min_samples_split': 5, 'min_samples_leaf': 7}. Best is trial 12 with value: 1057444.1939122414.
[I 2024-09-21 17:40:06,121] Trial 26 finished with value: 1057047.7086423486 and parameters: {'n_estimators': 407, 'max_depth': 15, 'min_samples_split': 4, 'min_samples_leaf': 10}. Best is trial 26 with value: 1057047.7086423486.
[I 2024-09-21 17:45:54,988] Trial 27 finished with value: 1058851.7334907858 and parameters: {'n_estimators': 405, 'max_depth': 11, 'min_samples_split': 7, 'min_samples_leaf': 8}. Best is trial 26 with value: 1057047.7086423486.
[I 2024-09-21 17:50:14,665] Trial 28 finished with value: 1062155.335495979 and parameters: {'n_estimators': 287, 'max_depth': 35, 'min_samples_split': 3, 'min_samples_leaf': 9}. Best is trial 26 with value: 1057047.7086423486.
[I 2024-09-21 17:54:13,103] Trial 29 finished with value: 1080225.344062824 and parameters: {'n_estimators': 209, 'max_depth': 18, 'min_samples_split': 6, 'min_samples_leaf': 5}. Best is trial 26 with value: 1057047.7086423486.
[I 2024-09-21 18:01:38,397] Trial 30 finished with value: 1075267.242839007 and parameters: {'n_estimators': 432, 'max_depth': 23, 'min_samples_split': 8, 'min_samples_leaf': 6}. Best is trial 26 with value: 1057047.7086423486.
[I 2024-09-21 18:06:35,388] Trial 31 finished with value: 1057344.262593508 and parameters: {'n_estimators': 341, 'max_depth': 65, 'min_samples_split': 4, 'min_samples_leaf': 10}. Best is trial 26 with value: 1057047.7086423486.
[I 2024-09-21 18:11:15,243] Trial 32 finished with value: 1057718.1694066303 and parameters: {'n_estimators': 322, 'max_depth': 65, 'min_samples_split': 5, 'min_samples_leaf': 10}. Best is trial 26 with value: 1057047.7086423486.
[I 2024-09-21 18:15:22,457] Trial 33 finished with value: 1062582.8846746618 and parameters: {'n_estimators': 274, 'max_depth': 48, 'min_samples_split': 6, 'min_samples_leaf': 9}. Best is trial 26 with value: 1057047.7086423486.
[I 2024-09-21 18:20:27,879] Trial 34 finished with value: 1057502.2763390748 and parameters: {'n_estimators': 350, 'max_depth': 57, 'min_samples_split': 4, 'min_samples_leaf': 10}. Best is trial 26 with value: 1057047.7086423486.
[I 2024-09-21 18:26:15,839] Trial 35 finished with value: 1061234.4941375898 and parameters: {'n_estimators': 387, 'max_depth': 56, 'min_samples_split': 3, 'min_samples_leaf': 9}. Best is trial 26 with value: 1057047.7086423486.
[I 2024-09-21 18:31:57,331] Trial 36 finished with value: 1065904.278045436 and parameters: {'n_estimators': 365, 'max_depth': 39, 'min_samples_split': 5, 'min_samples_leaf': 8}. Best is trial 26 with value: 1057047.7086423486.
[I 2024-09-21 18:39:50,500] Trial 37 finished with value: 1057971.8263342308 and parameters: {'n_estimators': 554, 'max_depth': 26, 'min_samples_split': 6, 'min_samples_leaf': 10}. Best is trial 26 with value: 1057047.7086423486.
[I 2024-09-21 18:49:26,339] Trial 38 finished with value: 1062444.1551558005 and parameters: {'n_estimators': 651, 'max_depth': 50, 'min_samples_split': 4, 'min_samples_leaf': 9}. Best is trial 26 with value: 1057047.7086423486.
[I 2024-09-21 18:58:05,135] Trial 39 finished with value: 1085387.2091594974 and parameters: {'n_estimators': 437, 'max_depth': 63, 'min_samples_split': 5, 'min_samples_leaf': 4}. Best is trial 26 with value: 1057047.7086423486.
[I 2024-09-21 19:00:35,139] Trial 40 finished with value: 1072583.4914802255 and parameters: {'n_estimators': 145, 'max_depth': 54, 'min_samples_split': 3, 'min_samples_leaf': 7}. Best is trial 26 with value: 1057047.7086423486.
[I 2024-09-21 19:05:01,766] Trial 41 finished with value: 1057788.6113972296 and parameters: {'n_estimators': 305, 'max_depth': 61, 'min_samples_split': 4, 'min_samples_leaf': 10}. Best is trial 26 with value: 1057047.7086423486.
[I 2024-09-21 19:08:32,008] Trial 42 finished with value: 1058922.056503226 and parameters: {'n_estimators': 241, 'max_depth': 57, 'min_samples_split': 4, 'min_samples_leaf': 10}. Best is trial 26 with value: 1057047.7086423486.
[I 2024-09-21 19:13:57,953] Trial 43 finished with value: 1061510.4728386654 and parameters: {'n_estimators': 362, 'max_depth': 69, 'min_samples_split': 5, 'min_samples_leaf': 9}. Best is trial 26 with value: 1057047.7086423486.
[I 2024-09-21 19:19:49,639] Trial 44 finished with value: 1057355.9545048159 and parameters: {'n_estimators': 411, 'max_depth': 44, 'min_samples_split': 4, 'min_samples_leaf': 10}. Best is trial 26 with value: 1057047.7086423486.
[I 2024-09-21 19:25:34,489] Trial 45 finished with value: 1057379.5021481279 and parameters: {'n_estimators': 405, 'max_depth': 32, 'min_samples_split': 2, 'min_samples_leaf': 10}. Best is trial 26 with value: 1057047.7086423486.
[I 2024-09-21 19:31:32,710] Trial 46 finished with value: 1061096.187894994 and parameters: {'n_estimators': 407, 'max_depth': 33, 'min_samples_split': 2, 'min_samples_leaf': 9}. Best is trial 26 with value: 1057047.7086423486.
[I 2024-09-21 19:38:43,726] Trial 47 finished with value: 1065911.0910603667 and parameters: {'n_estimators': 461, 'max_depth': 19, 'min_samples_split': 2, 'min_samples_leaf': 8}. Best is trial 26 with value: 1057047.7086423486.
[I 2024-09-21 19:46:10,780] Trial 48 finished with value: 1058141.687728325 and parameters: {'n_estimators': 525, 'max_depth': 29, 'min_samples_split': 3, 'min_samples_leaf': 10}. Best is trial 26 with value: 1057047.7086423486.
[I 2024-09-21 19:52:04,734] Trial 49 finished with value: 1057384.4129023652 and parameters: {'n_estimators': 416, 'max_depth': 39, 'min_samples_split': 2, 'min_samples_leaf': 10}. Best is trial 26 with value: 1057047.7086423486.
[I 2024-09-21 20:02:06,186] Trial 50 finished with value: 1096843.8435559727 and parameters: {'n_estimators': 409, 'max_depth': 43, 'min_samples_split': 2, 'min_samples_leaf': 2}. Best is trial 26 with value: 1057047.7086423486.
[I 2024-09-21 20:09:15,000] Trial 51 finished with value: 1057970.948071366 and parameters: {'n_estimators': 504, 'max_depth': 37, 'min_samples_split': 2, 'min_samples_leaf': 10}. Best is trial 26 with value: 1057047.7086423486.
[I 2024-09-21 20:15:15,580] Trial 52 finished with value: 1057696.1973264099 and parameters: {'n_estimators': 427, 'max_depth': 30, 'min_samples_split': 3, 'min_samples_leaf': 10}. Best is trial 26 with value: 1057047.7086423486.
[I 2024-09-21 20:20:58,850] Trial 53 finished with value: 1061252.6728290664 and parameters: {'n_estimators': 384, 'max_depth': 43, 'min_samples_split': 2, 'min_samples_leaf': 9}. Best is trial 26 with value: 1057047.7086423486.
[I 2024-09-21 20:27:36,767] Trial 54 finished with value: 1057497.7764479876 and parameters: {'n_estimators': 467, 'max_depth': 19, 'min_samples_split': 3, 'min_samples_leaf': 10}. Best is trial 26 with value: 1057047.7086423486.
[I 2024-09-21 20:32:55,808] Trial 55 finished with value: 1061105.5691715777 and parameters: {'n_estimators': 351, 'max_depth': 16, 'min_samples_split': 2, 'min_samples_leaf': 9}. Best is trial 26 with value: 1057047.7086423486.
[I 2024-09-21 20:40:03,289] Trial 56 finished with value: 1057967.1822161449 and parameters: {'n_estimators': 500, 'max_depth': 46, 'min_samples_split': 3, 'min_samples_leaf': 10}. Best is trial 26 with value: 1057047.7086423486.
[I 2024-09-21 20:48:23,418] Trial 57 finished with value: 1066542.8453869615 and parameters: {'n_estimators': 545, 'max_depth': 24, 'min_samples_split': 3, 'min_samples_leaf': 8}. Best is trial 26 with value: 1057047.7086423486.
[I 2024-09-21 20:55:17,616] Trial 58 finished with value: 1061554.9037747772 and parameters: {'n_estimators': 462, 'max_depth': 38, 'min_samples_split': 4, 'min_samples_leaf': 9}. Best is trial 26 with value: 1057047.7086423486.
[I 2024-09-21 21:01:15,847] Trial 59 finished with value: 1057430.026472612 and parameters: {'n_estimators': 417, 'max_depth': 51, 'min_samples_split': 2, 'min_samples_leaf': 10}. Best is trial 26 with value: 1057047.7086423486.
[I 2024-09-21 21:06:54,859] Trial 60 finished with value: 1061358.3852988072 and parameters: {'n_estimators': 379, 'max_depth': 51, 'min_samples_split': 7, 'min_samples_leaf': 9}. Best is trial 26 with value: 1057047.7086423486.
[I 2024-09-21 21:12:45,341] Trial 61 finished with value: 1057431.1180131433 and parameters: {'n_estimators': 415, 'max_depth': 41, 'min_samples_split': 2, 'min_samples_leaf': 10}. Best is trial 26 with value: 1057047.7086423486.
[I 2024-09-21 21:18:38,568] Trial 62 finished with value: 1057431.1180131433 and parameters: {'n_estimators': 415, 'max_depth': 46, 'min_samples_split': 2, 'min_samples_leaf': 10}. Best is trial 26 with value: 1057047.7086423486.
[I 2024-09-21 21:22:55,181] Trial 63 finished with value: 1058350.8849601168 and parameters: {'n_estimators': 298, 'max_depth': 41, 'min_samples_split': 2, 'min_samples_leaf': 10}. Best is trial 26 with value: 1057047.7086423486.
[I 2024-09-21 21:28:28,888] Trial 64 finished with value: 1057341.3761841345 and parameters: {'n_estimators': 389, 'max_depth': 34, 'min_samples_split': 2, 'min_samples_leaf': 10}. Best is trial 26 with value: 1057047.7086423486.
[I 2024-09-21 21:33:32,540] Trial 65 finished with value: 1061150.6634701982 and parameters: {'n_estimators': 334, 'max_depth': 32, 'min_samples_split': 2, 'min_samples_leaf': 9}. Best is trial 26 with value: 1057047.7086423486.
[I 2024-09-21 21:38:59,354] Trial 66 finished with value: 1057521.1931571523 and parameters: {'n_estimators': 375, 'max_depth': 35, 'min_samples_split': 8, 'min_samples_leaf': 10}. Best is trial 26 with value: 1057047.7086423486.
[I 2024-09-21 21:45:17,930] Trial 67 finished with value: 1057766.4702091774 and parameters: {'n_estimators': 448, 'max_depth': 28, 'min_samples_split': 2, 'min_samples_leaf': 10}. Best is trial 26 with value: 1057047.7086423486.
[I 2024-09-21 21:49:09,602] Trial 68 finished with value: 1062500.17675616 and parameters: {'n_estimators': 255, 'max_depth': 73, 'min_samples_split': 3, 'min_samples_leaf': 9}. Best is trial 26 with value: 1057047.7086423486.
[I 2024-09-21 21:56:35,303] Trial 69 finished with value: 1083719.9637704457 and parameters: {'n_estimators': 388, 'max_depth': 49, 'min_samples_split': 10, 'min_samples_leaf': 4}. Best is trial 26 with value: 1057047.7086423486.
[I 2024-09-21 22:01:38,278] Trial 70 finished with value: 1057410.0736538342 and parameters: {'n_estimators': 348, 'max_depth': 53, 'min_samples_split': 4, 'min_samples_leaf': 10}. Best is trial 26 with value: 1057047.7086423486.
[I 2024-09-21 22:06:39,696] Trial 71 finished with value: 1057412.8511689315 and parameters: {'n_estimators': 346, 'max_depth': 54, 'min_samples_split': 4, 'min_samples_leaf': 10}. Best is trial 26 with value: 1057047.7086423486.
[I 2024-09-21 22:11:39,650] Trial 72 finished with value: 1057413.328415381 and parameters: {'n_estimators': 343, 'max_depth': 53, 'min_samples_split': 4, 'min_samples_leaf': 10}. Best is trial 26 with value: 1057047.7086423486.
[I 2024-09-21 22:16:22,980] Trial 73 finished with value: 1057509.8829883935 and parameters: {'n_estimators': 326, 'max_depth': 59, 'min_samples_split': 5, 'min_samples_leaf': 10}. Best is trial 26 with value: 1057047.7086423486.
[I 2024-09-21 22:20:46,989] Trial 74 finished with value: 1058869.2953636541 and parameters: {'n_estimators': 300, 'max_depth': 12, 'min_samples_split': 4, 'min_samples_leaf': 9}. Best is trial 26 with value: 1057047.7086423486.
[I 2024-09-21 22:26:11,038] Trial 75 finished with value: 1061553.467223997 and parameters: {'n_estimators': 363, 'max_depth': 45, 'min_samples_split': 5, 'min_samples_leaf': 9}. Best is trial 26 with value: 1057047.7086423486.
[I 2024-09-21 22:26:31,305] Trial 76 finished with value: 1062345.9574859936 and parameters: {'n_estimators': 14, 'max_depth': 63, 'min_samples_split': 4, 'min_samples_leaf': 10}. Best is trial 26 with value: 1057047.7086423486.
[I 2024-09-21 22:27:55,022] Trial 77 finished with value: 1075391.400601512 and parameters: {'n_estimators': 70, 'max_depth': 37, 'min_samples_split': 4, 'min_samples_leaf': 6}. Best is trial 26 with value: 1057047.7086423486.
[I 2024-09-21 22:31:53,079] Trial 78 finished with value: 1059097.6184597344 and parameters: {'n_estimators': 275, 'max_depth': 55, 'min_samples_split': 4, 'min_samples_leaf': 10}. Best is trial 26 with value: 1057047.7086423486.
[I 2024-09-21 22:37:41,011] Trial 79 finished with value: 1061187.7441288743 and parameters: {'n_estimators': 389, 'max_depth': 48, 'min_samples_split': 5, 'min_samples_leaf': 9}. Best is trial 26 with value: 1057047.7086423486.
[I 2024-09-21 22:43:54,771] Trial 80 finished with value: 1057929.9362408498 and parameters: {'n_estimators': 442, 'max_depth': 23, 'min_samples_split': 3, 'min_samples_leaf': 10}. Best is trial 26 with value: 1057047.7086423486.
[I 2024-09-21 22:48:58,012] Trial 81 finished with value: 1057448.2960929426 and parameters: {'n_estimators': 347, 'max_depth': 52, 'min_samples_split': 4, 'min_samples_leaf': 10}. Best is trial 26 with value: 1057047.7086423486.
[I 2024-09-21 22:53:27,993] Trial 82 finished with value: 1057791.4447301684 and parameters: {'n_estimators': 313, 'max_depth': 54, 'min_samples_split': 5, 'min_samples_leaf': 10}. Best is trial 26 with value: 1057047.7086423486.
[I 2024-09-21 22:58:30,041] Trial 83 finished with value: 1057413.328415381 and parameters: {'n_estimators': 343, 'max_depth': 60, 'min_samples_split': 4, 'min_samples_leaf': 10}. Best is trial 26 with value: 1057047.7086423486.
[I 2024-09-21 23:05:16,301] Trial 84 finished with value: 1079621.324577621 and parameters: {'n_estimators': 367, 'max_depth': 40, 'min_samples_split': 3, 'min_samples_leaf': 5}. Best is trial 26 with value: 1057047.7086423486.
[I 2024-09-21 23:10:52,817] Trial 85 finished with value: 1057579.9457712371 and parameters: {'n_estimators': 397, 'max_depth': 64, 'min_samples_split': 4, 'min_samples_leaf': 10}. Best is trial 26 with value: 1057047.7086423486.
[I 2024-09-21 23:16:15,891] Trial 86 finished with value: 1061197.3642422075 and parameters: {'n_estimators': 354, 'max_depth': 67, 'min_samples_split': 4, 'min_samples_leaf': 9}. Best is trial 26 with value: 1057047.7086423486.

AssertionError: Should not reach.

In [42]:
study.best_params

{'n_estimators': 407,
 'max_depth': 15,
 'min_samples_split': 4,
 'min_samples_leaf': 10}

In [40]:
study.best_value

1057047.7086423486

In [41]:
study.best_trial

FrozenTrial(number=26, state=1, values=[1057047.7086423486], datetime_start=datetime.datetime(2024, 9, 21, 17, 34, 23, 114537), datetime_complete=datetime.datetime(2024, 9, 21, 17, 40, 6, 60059), params={'n_estimators': 407, 'max_depth': 15, 'min_samples_split': 4, 'min_samples_leaf': 10}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'n_estimators': IntDistribution(high=700, log=False, low=0, step=1), 'max_depth': IntDistribution(high=100, log=False, low=10, step=1), 'min_samples_split': IntDistribution(high=10, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=10, log=False, low=1, step=1)}, trial_id=27, value=None)

In [46]:
# use the best hyperparameters to train the model   

best_params = study.best_params
best_params

rf_model = RandomForestRegressor(
    # n_estimators=best_params['n_estimators'],
    # max_depth=best_params['max_depth'],
    # min_samples_split=best_params['min_samples_split'],
    # min_samples_leaf=best_params['min_samples_leaf'],
    n_estimators= 604,
    max_depth=10,
    min_samples_split=2,
    min_samples_leaf=6,
    n_jobs=-1,
    random_state=42
)

train_mse, train_mae, train_r2 = [], [], []
test_mse, test_mae, test_r2 = [], [], []

for train_index, test_index in kf.split(X_yield):
    X_train, X_test = X_yield.iloc[train_index], X_yield.iloc[test_index]
    y_train, y_test = y_yield.iloc[train_index], y_yield.iloc[test_index]

    rf_model.fit(X_train, y_train)

    y_pred_test = rf_model.predict(X_test)
    y_pred_train = rf_model.predict(X_train)

    test_mse.append(mean_squared_error(y_test, y_pred_test))
    test_mae.append(mean_absolute_error(y_test, y_pred_test))
    test_r2.append(r2_score(y_test, y_pred_test))

    train_mse.append(mean_squared_error(y_train, y_pred_train))
    train_mae.append(mean_absolute_error(y_train, y_pred_train))
    train_r2.append(r2_score(y_train, y_pred_train))

In [47]:
print(f'Train MSE: {np.mean(train_mse):.2f}')
print(f'Train RMSE: {np.sqrt(np.mean(train_mse)):.2f}')
print(f'Train MAE: {np.mean(train_mae):.2f}')
print(f'Train R2: {np.mean(train_r2):.2f}\n')
print(f'Standard deviation of Train MSE: {np.std(train_mse):.2f}\n')

print(f'Test MSE: {np.mean(test_mse):.2f}')
print(f'Test RMSE: {np.sqrt(np.mean(test_mse)):.2f}')
print(f'Test MAE: {np.mean(test_mae):.2f}')
print(f'Test R2: {np.mean(test_r2):.2f}')
print(f'Standard deviation of Test MSE: {np.std(test_mse):.2f}')

Train MSE: 713441.01
Train RMSE: 844.65
Train MAE: 685.24
Train R2: 0.42

Standard deviation of Train MSE: 19450.84

Test MSE: 1060241.42
Test RMSE: 1029.68
Test MAE: 843.91
Test R2: 0.14
Standard deviation of Test MSE: 36226.93